//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.AboutResources", typeof(AboutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti is a free universal file manager that allows you to access all your files no matter where they are, and perform countless actions such as upload, download, copy, move, delete, share, send by email, SMS or Bluetooth, among others. And if you forgot where your files are, don&apos;t worry, Woopiti has a search engine that searches across all your accounts..
        /// </summary>
        public static string ApplicationPresentation {
            get {
                return ResourceManager.GetString("ApplicationPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti connects to Internet to download the information, consider the service provider could apply charges because of the use of your data connection..
        /// </summary>
        public static string ConnectionChargesMessage {
            get {
                return ResourceManager.GetString("ConnectionChargesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@woopiti.com.
        /// </summary>
        public static string ContactMail {
            get {
                return ResourceManager.GetString("ContactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactMailLabel {
            get {
                return ResourceManager.GetString("ContactMailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive, Dropbox, OneDrive, Flickr, Google Photos, Youtube, Box, Twitter, Instagram, Mega.co.nz, CloudMe, HiDrive, 4Shared , WebDav, OwnCloud.
        /// </summary>
        public static string ProvidersList {
            get {
                return ResourceManager.GetString("ProvidersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.woopiti.com.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebsiteLabel {
            get {
                return ResourceManager.GetString("WebsiteLabel", resourceCulture);
            }
        }
    }
}
