//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AutomaticLabel {
            get {
                return ResourceManager.GetString("AutomaticLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up accounts automatically from the information in the device.
        /// </summary>
        public static string AutomaticMessage {
            get {
                return ResourceManager.GetString("AutomaticMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are available updates..
        /// </summary>
        public static string AvailableUpdatesMessage {
            get {
                return ResourceManager.GetString("AvailableUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdatesMessage {
            get {
                return ResourceManager.GetString("CheckingForUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        public static string ClearSelectionLabel {
            get {
                return ResourceManager.GetString("ClearSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of the accounts below to see and manage your files..
        /// </summary>
        public static string ConnectMessage {
            get {
                return ResourceManager.GetString("ConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates {0:P0}....
        /// </summary>
        public static string DownloadingUpdatesMessage {
            get {
                return ResourceManager.GetString("DownloadingUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications must be enabled to proceed. Please change the notificaton settings of your device..
        /// </summary>
        public static string EnableNotificationsMessage {
            get {
                return ResourceManager.GetString("EnableNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works?.
        /// </summary>
        public static string HowItWorksLabel {
            get {
                return ResourceManager.GetString("HowItWorksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti asks for access for each of the cloud storage services and social networks you want to add. 
        ///If the service provides a web site to authenticate, you will be directed to it, where you must login and conseder permissions to this application to access your information. After this process Woopiti gets and save an access token which you can revoke at any time in the service site.
        ///If the service do not have a website to authenticate the user and password are requested and stored locally.
        ///In all cases,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowItWorksMessage {
            get {
                return ResourceManager.GetString("HowItWorksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing updates....
        /// </summary>
        public static string InstallingUpdatesMessage {
            get {
                return ResourceManager.GetString("InstallingUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the udpates failed..
        /// </summary>
        public static string InstallUpdatesFailedMessage {
            get {
                return ResourceManager.GetString("InstallUpdatesFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to list mode.
        /// </summary>
        public static string ListModeMessage {
            get {
                return ResourceManager.GetString("ListModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when loading the data..
        /// </summary>
        public static string LoadingDataError {
            get {
                return ResourceManager.GetString("LoadingDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app must be updated before continuing..
        /// </summary>
        public static string MandatoryUpdatesMessage {
            get {
                return ResourceManager.GetString("MandatoryUpdatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string ManualLabel {
            get {
                return ResourceManager.GetString("ManualLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti will start in offline mode because Internet service is not available. 
        ///You can return to online mode from the main menu at any time..
        /// </summary>
        public static string OfflineModeMessage {
            get {
                return ResourceManager.GetString("OfflineModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        public static string OpenContainingFolderLabel {
            get {
                return ResourceManager.GetString("OpenContainingFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be opened..
        /// </summary>
        public static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti allows you to link your accounts and see all your files in one place.
        /// </summary>
        public static string PresentationMessage {
            get {
                return ResourceManager.GetString("PresentationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review.
        /// </summary>
        public static string RateAndReviewLabel {
            get {
                return ResourceManager.GetString("RateAndReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to rate this app?.
        /// </summary>
        public static string RateAppQuestion {
            get {
                return ResourceManager.GetString("RateAppQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove advertising.
        /// </summary>
        public static string RemoveAdsLabel {
            get {
                return ResourceManager.GetString("RemoveAdsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application.
        /// </summary>
        public static string SelectAppLabel {
            get {
                return ResourceManager.GetString("SelectAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        public static string SelectedItemMessage {
            get {
                return ResourceManager.GetString("SelectedItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        public static string SelectedItemsMessage {
            get {
                return ResourceManager.GetString("SelectedItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to share the file..
        /// </summary>
        public static string ShareErrorMessage {
            get {
                return ResourceManager.GetString("ShareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string SizeProgressMessage {
            get {
                return ResourceManager.GetString("SizeProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SkipLabel {
            get {
                return ResourceManager.GetString("SkipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string SortByDateAscLabel {
            get {
                return ResourceManager.GetString("SortByDateAscLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string SortByDateDescLabel {
            get {
                return ResourceManager.GetString("SortByDateDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SortByNameAscLabel {
            get {
                return ResourceManager.GetString("SortByNameAscLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name descending.
        /// </summary>
        public static string SortByNameDescLabel {
            get {
                return ResourceManager.GetString("SortByNameDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest.
        /// </summary>
        public static string SortBySizeAscLabel {
            get {
                return ResourceManager.GetString("SortBySizeAscLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biggest.
        /// </summary>
        public static string SortBySizeDescLabel {
            get {
                return ResourceManager.GetString("SortBySizeDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to tiles mode.
        /// </summary>
        public static string TilesModeMessage {
            get {
                return ResourceManager.GetString("TilesModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        public static string UnselectLabel {
            get {
                return ResourceManager.GetString("UnselectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
