//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileSystemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileSystemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.FileSystemResources", typeof(FileSystemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be copied..
        /// </summary>
        public static string CopyFileError {
            get {
                return ResourceManager.GetString("CopyFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be copied..
        /// </summary>
        public static string CopyFilesError {
            get {
                return ResourceManager.GetString("CopyFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were copied..
        /// </summary>
        public static string CopyFilesSucceded {
            get {
                return ResourceManager.GetString("CopyFilesSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was copied..
        /// </summary>
        public static string CopyFileSucceded {
            get {
                return ResourceManager.GetString("CopyFileSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder could not be copied..
        /// </summary>
        public static string CopyFolderError {
            get {
                return ResourceManager.GetString("CopyFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders could not be copied..
        /// </summary>
        public static string CopyFoldersError {
            get {
                return ResourceManager.GetString("CopyFoldersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders were copied..
        /// </summary>
        public static string CopyFoldersSucceded {
            get {
                return ResourceManager.GetString("CopyFoldersSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was copied..
        /// </summary>
        public static string CopyFolderSucceded {
            get {
                return ResourceManager.GetString("CopyFolderSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy here.
        /// </summary>
        public static string CopyHereLabel {
            get {
                return ResourceManager.GetString("CopyHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items could not be copied..
        /// </summary>
        public static string CopyItemsError {
            get {
                return ResourceManager.GetString("CopyItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items were copied..
        /// </summary>
        public static string CopyItemsSucceded {
            get {
                return ResourceManager.GetString("CopyItemsSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyLabel {
            get {
                return ResourceManager.GetString("CopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        public static string CreatedDateLabel {
            get {
                return ResourceManager.GetString("CreatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder could not be created..
        /// </summary>
        public static string CreateFolderError {
            get {
                return ResourceManager.GetString("CreateFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string CreateFolderLabel {
            get {
                return ResourceManager.GetString("CreateFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be deleted..
        /// </summary>
        public static string DeleteFileError {
            get {
                return ResourceManager.GetString("DeleteFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteFileQuestion {
            get {
                return ResourceManager.GetString("DeleteFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be deleted..
        /// </summary>
        public static string DeleteFilesError {
            get {
                return ResourceManager.GetString("DeleteFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these {0} files?.
        /// </summary>
        public static string DeleteFilesQuestion {
            get {
                return ResourceManager.GetString("DeleteFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder could not be deleted..
        /// </summary>
        public static string DeleteFolderError {
            get {
                return ResourceManager.GetString("DeleteFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the folder &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteFolderQuestion {
            get {
                return ResourceManager.GetString("DeleteFolderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders could not be deleted..
        /// </summary>
        public static string DeleteFoldersError {
            get {
                return ResourceManager.GetString("DeleteFoldersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these {0} folders?.
        /// </summary>
        public static string DeleteFoldersQuestion {
            get {
                return ResourceManager.GetString("DeleteFoldersQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be downloaded..
        /// </summary>
        public static string DownloadFileError {
            get {
                return ResourceManager.GetString("DownloadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; can not be downloaded. .
        /// </summary>
        public static string DownloadFileForbidden {
            get {
                return ResourceManager.GetString("DownloadFileForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file {0}will be downloaded and saved in the phone..
        /// </summary>
        public static string DownloadFileMessage {
            get {
                return ResourceManager.GetString("DownloadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be downloaded..
        /// </summary>
        public static string DownloadFilesError {
            get {
                return ResourceManager.GetString("DownloadFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files can not be downloaded..
        /// </summary>
        public static string DownloadFilesForbidden {
            get {
                return ResourceManager.GetString("DownloadFilesForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files {1}will be downloaded and saved in the phone..
        /// </summary>
        public static string DownloadFilesMessage {
            get {
                return ResourceManager.GetString("DownloadFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were downloaded..
        /// </summary>
        public static string DownloadFilesSucceded {
            get {
                return ResourceManager.GetString("DownloadFilesSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was downloaded..
        /// </summary>
        public static string DownloadFileSucceded {
            get {
                return ResourceManager.GetString("DownloadFileSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders were downloaded..
        /// </summary>
        public static string DownloadFoldersSucceded {
            get {
                return ResourceManager.GetString("DownloadFoldersSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was downloaded..
        /// </summary>
        public static string DownloadFolderSucceded {
            get {
                return ResourceManager.GetString("DownloadFolderSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download here.
        /// </summary>
        public static string DownloadHereLabel {
            get {
                return ResourceManager.GetString("DownloadHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items were downloaded..
        /// </summary>
        public static string DownloadItemsSucceded {
            get {
                return ResourceManager.GetString("DownloadItemsSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadLabel {
            get {
                return ResourceManager.GetString("DownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists..
        /// </summary>
        public static string DuplicatedFileError {
            get {
                return ResourceManager.GetString("DuplicatedFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder with the same name already exists..
        /// </summary>
        public static string DuplicatedFolderError {
            get {
                return ResourceManager.GetString("DuplicatedFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same name already exists..
        /// </summary>
        public static string DuplicatedItemError {
            get {
                return ResourceManager.GetString("DuplicatedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items with the same name already exists..
        /// </summary>
        public static string DuplicatedItemsError {
            get {
                return ResourceManager.GetString("DuplicatedItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no files in this folder..
        /// </summary>
        public static string EmptyFolderMessage {
            get {
                return ResourceManager.GetString("EmptyFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty trash.
        /// </summary>
        public static string EmptyTrashLabel {
            get {
                return ResourceManager.GetString("EmptyTrashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to empty the trash?.
        /// </summary>
        public static string EmptyTrashQuestion {
            get {
                return ResourceManager.GetString("EmptyTrashQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep existing files.
        /// </summary>
        public static string KeepExistingFilesMessage {
            get {
                return ResourceManager.GetString("KeepExistingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified date.
        /// </summary>
        public static string ModifiedDateLabel {
            get {
                return ResourceManager.GetString("ModifiedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be moved..
        /// </summary>
        public static string MoveFileError {
            get {
                return ResourceManager.GetString("MoveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be moved..
        /// </summary>
        public static string MoveFilesError {
            get {
                return ResourceManager.GetString("MoveFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were moved..
        /// </summary>
        public static string MoveFilesSucceded {
            get {
                return ResourceManager.GetString("MoveFilesSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was moved..
        /// </summary>
        public static string MoveFileSucceded {
            get {
                return ResourceManager.GetString("MoveFileSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder could not be moved..
        /// </summary>
        public static string MoveFolderError {
            get {
                return ResourceManager.GetString("MoveFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders could not be moved..
        /// </summary>
        public static string MoveFoldersError {
            get {
                return ResourceManager.GetString("MoveFoldersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} folders were moved..
        /// </summary>
        public static string MoveFoldersSucceded {
            get {
                return ResourceManager.GetString("MoveFoldersSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was moved..
        /// </summary>
        public static string MoveFolderSucceded {
            get {
                return ResourceManager.GetString("MoveFolderSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move here.
        /// </summary>
        public static string MoveHereLabel {
            get {
                return ResourceManager.GetString("MoveHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items could not be moved..
        /// </summary>
        public static string MoveItemsError {
            get {
                return ResourceManager.GetString("MoveItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items were moved..
        /// </summary>
        public static string MoveItemsSucceded {
            get {
                return ResourceManager.GetString("MoveItemsSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string MoveLabel {
            get {
                return ResourceManager.GetString("MoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet service is not available.
        ///Check your cellular data of Wi-Fi connection..
        /// </summary>
        public static string NetworkUnavailableMessage {
            get {
                return ResourceManager.GetString("NetworkUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not available in offline mode..
        /// </summary>
        public static string NotCachedFolderMessage {
            get {
                return ResourceManager.GetString("NotCachedFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online mode.
        /// </summary>
        public static string OnlineModeLabel {
            get {
                return ResourceManager.GetString("OnlineModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenLabel {
            get {
                return ResourceManager.GetString("OpenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesLabel {
            get {
                return ResourceManager.GetString("PropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files.
        /// </summary>
        public static string RenameFilesMessage {
            get {
                return ResourceManager.GetString("RenameFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredLabel {
            get {
                return ResourceManager.GetString("RequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files could not be saved..
        /// </summary>
        public static string SaveFilesError {
            get {
                return ResourceManager.GetString("SaveFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a different folder..
        /// </summary>
        public static string SelectDifferentFolderMessage {
            get {
                return ResourceManager.GetString("SelectDifferentFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareLabel {
            get {
                return ResourceManager.GetString("ShareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeLabel {
            get {
                return ResourceManager.GetString("SizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file.
        /// </summary>
        public static string UnknownFileLabel {
            get {
                return ResourceManager.GetString("UnknownFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be updated..
        /// </summary>
        public static string UpdateFileError {
            get {
                return ResourceManager.GetString("UpdateFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder could not be updated..
        /// </summary>
        public static string UpdateFolderError {
            get {
                return ResourceManager.GetString("UpdateFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be uploaded..
        /// </summary>
        public static string UploadFileError {
            get {
                return ResourceManager.GetString("UploadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files could not be uploaded..
        /// </summary>
        public static string UploadFilesError {
            get {
                return ResourceManager.GetString("UploadFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        public static string UploadFilesLabel {
            get {
                return ResourceManager.GetString("UploadFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were uploaded..
        /// </summary>
        public static string UploadFilesSucceded {
            get {
                return ResourceManager.GetString("UploadFilesSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was uploaded..
        /// </summary>
        public static string UploadFileSucceded {
            get {
                return ResourceManager.GetString("UploadFileSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload here.
        /// </summary>
        public static string UploadHereLabel {
            get {
                return ResourceManager.GetString("UploadHereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadLabel {
            get {
                return ResourceManager.GetString("UploadLabel", resourceCulture);
            }
        }
    }
}
