//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem while trying to link the account..
        /// </summary>
        public static string AddAccountError {
            get {
                return ResourceManager.GetString("AddAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link account.
        /// </summary>
        public static string AddAccountLabel {
            get {
                return ResourceManager.GetString("AddAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string AuthenticateLabel {
            get {
                return ResourceManager.GetString("AuthenticateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalculateLabel {
            get {
                return ResourceManager.GetString("CalculateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 file {0}will be downloaded and uploaded to the new location..
        /// </summary>
        public static string CopyFileQuestion {
            get {
                return ResourceManager.GetString("CopyFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files {1}will be downloaded and uploaded to the new location..
        /// </summary>
        public static string CopyFilesQuestion {
            get {
                return ResourceManager.GetString("CopyFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create album.
        /// </summary>
        public static string CreateAlbumLabel {
            get {
                return ResourceManager.GetString("CreateAlbumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the album &quot;{0}&quot; and all its photos from {1}?.
        /// </summary>
        public static string DeleteAlbumQuestion {
            get {
                return ResourceManager.GetString("DeleteAlbumQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} albums and all its photos from {1}?.
        /// </summary>
        public static string DeleteAlbumsQuestion {
            get {
                return ResourceManager.GetString("DeleteAlbumsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the file &quot;{0}&quot; from {1}?.
        /// </summary>
        public static string DeleteFileQuestion {
            get {
                return ResourceManager.GetString("DeleteFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} files from {1}?.
        /// </summary>
        public static string DeleteFilesQuestion {
            get {
                return ResourceManager.GetString("DeleteFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the folder &quot;{0}&quot; and all its content from {1}?.
        /// </summary>
        public static string DeleteFolderQuestion {
            get {
                return ResourceManager.GetString("DeleteFolderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} folders from {1}?.
        /// </summary>
        public static string DeleteFoldersQuestion {
            get {
                return ResourceManager.GetString("DeleteFoldersQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the photo &quot;{0}&quot; from {1}?.
        /// </summary>
        public static string DeletePhotoQuestion {
            get {
                return ResourceManager.GetString("DeletePhotoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} photos from {1}?.
        /// </summary>
        public static string DeletePhotosQuestion {
            get {
                return ResourceManager.GetString("DeletePhotosQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no photos in this album..
        /// </summary>
        public static string EmptyAlbumMessage {
            get {
                return ResourceManager.GetString("EmptyAlbumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no linked accounts..
        /// </summary>
        public static string NoLinkedAccountsMessage {
            get {
                return ResourceManager.GetString("NoLinkedAccountsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder do not accept files..
        /// </summary>
        public static string NotSupportedFilesMessage {
            get {
                return ResourceManager.GetString("NotSupportedFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder do not accept that kind of file..
        /// </summary>
        public static string NotSupportedFileTypeMessage {
            get {
                return ResourceManager.GetString("NotSupportedFileTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create folders here..
        /// </summary>
        public static string NotSupportedFoldersMessage {
            get {
                return ResourceManager.GetString("NotSupportedFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in {0}.
        /// </summary>
        public static string OpenInLabel {
            get {
                return ResourceManager.GetString("OpenInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove account.
        /// </summary>
        public static string RemoveAccountLabel {
            get {
                return ResourceManager.GetString("RemoveAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the account &quot;{0}&quot; ?.
        /// </summary>
        public static string RemoveAccountQuestion {
            get {
                return ResourceManager.GetString("RemoveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove accounts.
        /// </summary>
        public static string RemoveAccountsLabel {
            get {
                return ResourceManager.GetString("RemoveAccountsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} accounts?.
        /// </summary>
        public static string RemoveAccountsQuestion {
            get {
                return ResourceManager.GetString("RemoveAccountsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin from Start.
        /// </summary>
        public static string UnpinFromStart {
            get {
                return ResourceManager.GetString("UnpinFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photos.
        /// </summary>
        public static string UploadPhotosLabel {
            get {
                return ResourceManager.GetString("UploadPhotosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload videos.
        /// </summary>
        public static string UploadVideosLabel {
            get {
                return ResourceManager.GetString("UploadVideosLabel", resourceCulture);
            }
        }
    }
}
