//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgressResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgressResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.ProgressResources", typeof(ProgressResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0}.
        /// </summary>
        public static string CopyFileMessage {
            get {
                return ResourceManager.GetString("CopyFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy folder {0}.
        /// </summary>
        public static string CopyFolderMessage {
            get {
                return ResourceManager.GetString("CopyFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}....
        /// </summary>
        public static string CopyingFileMessage {
            get {
                return ResourceManager.GetString("CopyingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} files....
        /// </summary>
        public static string CopyingFilesMessage {
            get {
                return ResourceManager.GetString("CopyingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying folder {0}....
        /// </summary>
        public static string CopyingFolderMessage {
            get {
                return ResourceManager.GetString("CopyingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0} folders....
        /// </summary>
        public static string CopyingFoldersMessage {
            get {
                return ResourceManager.GetString("CopyingFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder {0}.
        /// </summary>
        public static string CreateFolderMessage {
            get {
                return ResourceManager.GetString("CreateFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder {0}....
        /// </summary>
        public static string CreatingFolderMessage {
            get {
                return ResourceManager.GetString("CreatingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} folders....
        /// </summary>
        public static string CreatingFoldersMessage {
            get {
                return ResourceManager.GetString("CreatingFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteFileMessage {
            get {
                return ResourceManager.GetString("DeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string DeleteFolderMessage {
            get {
                return ResourceManager.GetString("DeleteFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}....
        /// </summary>
        public static string DeletingFileMessage {
            get {
                return ResourceManager.GetString("DeletingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} files....
        /// </summary>
        public static string DeletingFilesMessage {
            get {
                return ResourceManager.GetString("DeletingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}....
        /// </summary>
        public static string DeletingFolderMessage {
            get {
                return ResourceManager.GetString("DeletingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0} folders....
        /// </summary>
        public static string DeletingFoldersMessage {
            get {
                return ResourceManager.GetString("DeletingFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0}.
        /// </summary>
        public static string DownloadFileMessage {
            get {
                return ResourceManager.GetString("DownloadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data....
        /// </summary>
        public static string DownloadingDataMessage {
            get {
                return ResourceManager.GetString("DownloadingDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}....
        /// </summary>
        public static string DownloadingFileMessage {
            get {
                return ResourceManager.GetString("DownloadingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} files....
        /// </summary>
        public static string DownloadingFilesMessage {
            get {
                return ResourceManager.GetString("DownloadingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading thumbnail of {0}.
        /// </summary>
        public static string DownloadingThumbnailMessage {
            get {
                return ResourceManager.GetString("DownloadingThumbnailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading thumbnails....
        /// </summary>
        public static string DownloadingThumbnailsMessage {
            get {
                return ResourceManager.GetString("DownloadingThumbnailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download thumbnail of {0}.
        /// </summary>
        public static string DownloadThumbnailMessage {
            get {
                return ResourceManager.GetString("DownloadThumbnailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string InitializingMessage {
            get {
                return ResourceManager.GetString("InitializingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        public static string LoadingItemMessage {
            get {
                return ResourceManager.GetString("LoadingItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0}.
        /// </summary>
        public static string MoveFileMessage {
            get {
                return ResourceManager.GetString("MoveFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move folder {0}.
        /// </summary>
        public static string MoveFolderMessage {
            get {
                return ResourceManager.GetString("MoveFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0}....
        /// </summary>
        public static string MovingFileMessage {
            get {
                return ResourceManager.GetString("MovingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} files....
        /// </summary>
        public static string MovingFilesMessage {
            get {
                return ResourceManager.GetString("MovingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving folder {0}....
        /// </summary>
        public static string MovingFolderMessage {
            get {
                return ResourceManager.GetString("MovingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving {0} folders....
        /// </summary>
        public static string MovingFoldersMessage {
            get {
                return ResourceManager.GetString("MovingFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pending actions.
        /// </summary>
        public static string NoPendingActionsMesssage {
            get {
                return ResourceManager.GetString("NoPendingActionsMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0}....
        /// </summary>
        public static string OpeningFolderMessage {
            get {
                return ResourceManager.GetString("OpeningFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string OperationCanceledMessage {
            get {
                return ResourceManager.GetString("OperationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string OperationCompletedMessage {
            get {
                return ResourceManager.GetString("OperationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faulted.
        /// </summary>
        public static string OperationFaultedMessage {
            get {
                return ResourceManager.GetString("OperationFaultedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string OperationNotStartedMessage {
            get {
                return ResourceManager.GetString("OperationNotStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending actions....
        /// </summary>
        public static string PendingActionsLabel {
            get {
                return ResourceManager.GetString("PendingActionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} actions in progress....
        /// </summary>
        public static string PendingActionsMessage {
            get {
                return ResourceManager.GetString("PendingActionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching &apos;{0}&apos;....
        /// </summary>
        public static string SearchingMessage {
            get {
                return ResourceManager.GetString("SearchingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop downloading file {0}?.
        /// </summary>
        public static string StopDownloadingFileQuestion {
            get {
                return ResourceManager.GetString("StopDownloadingFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        public static string UpdateFileMessage {
            get {
                return ResourceManager.GetString("UpdateFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update folder {0}.
        /// </summary>
        public static string UpdateFolderMessage {
            get {
                return ResourceManager.GetString("UpdateFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}....
        /// </summary>
        public static string UpdatingFileMessage {
            get {
                return ResourceManager.GetString("UpdatingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} files....
        /// </summary>
        public static string UpdatingFilesMessage {
            get {
                return ResourceManager.GetString("UpdatingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating folder {0}....
        /// </summary>
        public static string UpdatingFolderMessage {
            get {
                return ResourceManager.GetString("UpdatingFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} folders....
        /// </summary>
        public static string UpdatingFoldersMessage {
            get {
                return ResourceManager.GetString("UpdatingFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload {0}.
        /// </summary>
        public static string UploadFileMessage {
            get {
                return ResourceManager.GetString("UploadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0}....
        /// </summary>
        public static string UploadingFileMessage {
            get {
                return ResourceManager.GetString("UploadingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading {0} files....
        /// </summary>
        public static string UploadingFilesMessage {
            get {
                return ResourceManager.GetString("UploadingFilesMessage", resourceCulture);
            }
        }
    }
}
