//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveLabel {
            get {
                return ResourceManager.GetString("ActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} available..
        /// </summary>
        public static string AvailableSpaceMessage {
            get {
                return ResourceManager.GetString("AvailableSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string CacheLabel {
            get {
                return ResourceManager.GetString("CacheLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti cache downloaded files internally to avoid downloading duplicated files and make an efficient use of the internet connection. 
        ///You might want to clear the cache if a file was modified externally..
        /// </summary>
        public static string CacheMessage {
            get {
                return ResourceManager.GetString("CacheMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string CalculatingMessage {
            get {
                return ResourceManager.GetString("CalculatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change code.
        /// </summary>
        public static string ChangeCodeLabel {
            get {
                return ResourceManager.GetString("ChangeCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCacheLabel {
            get {
                return ResourceManager.GetString("ClearCacheLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new 4-digit passcode.
        /// </summary>
        public static string EnterNewPasscodeMessage {
            get {
                return ResourceManager.GetString("EnterNewPasscodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 4-digit passcode.
        /// </summary>
        public static string EnterPasscodeMessage {
            get {
                return ResourceManager.GetString("EnterPasscodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string InactiveLabel {
            get {
                return ResourceManager.GetString("InactiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passcode.
        /// </summary>
        public static string InvalidPasscodeMessage {
            get {
                return ResourceManager.GetString("InvalidPasscodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passcode.
        /// </summary>
        public static string PasscodeLabel {
            get {
                return ResourceManager.GetString("PasscodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be prompted for a 4-digit passcode that you will have to enter to start the app..
        /// </summary>
        public static string PasscodeMessage {
            get {
                return ResourceManager.GetString("PasscodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo labels.
        /// </summary>
        public static string PhotoLabelsLabel {
            get {
                return ResourceManager.GetString("PhotoLabelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show labels on photo tiles.
        /// </summary>
        public static string PhotoLabelsMessage {
            get {
                return ResourceManager.GetString("PhotoLabelsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter the 4-digit passcode..
        /// </summary>
        public static string ReEnterPasscodeMessage {
            get {
                return ResourceManager.GetString("ReEnterPasscodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request code.
        /// </summary>
        public static string RequestCodeLabel {
            get {
                return ResourceManager.GetString("RequestCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woopiti requires you to authenticate before using the app..
        /// </summary>
        public static string RequiresAuthenticationMessage {
            get {
                return ResourceManager.GetString("RequiresAuthenticationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        public static string TermsOfUseLabel {
            get {
                return ResourceManager.GetString("TermsOfUseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.woopiti.com/TermsOfUse.
        /// </summary>
        public static string TermsOfUseLink {
            get {
                return ResourceManager.GetString("TermsOfUseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent start tiles.
        /// </summary>
        public static string TransparentStartTilesLabel {
            get {
                return ResourceManager.GetString("TransparentStartTilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} used..
        /// </summary>
        public static string UsedSpaceMessage {
            get {
                return ResourceManager.GetString("UsedSpaceMessage", resourceCulture);
            }
        }
    }
}
