//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubscriptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.SubscriptionResources", typeof(SubscriptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already purchased subscription?.
        /// </summary>
        public static string AlreadPurchasedSubscriptionQuestion {
            get {
                return ResourceManager.GetString("AlreadPurchasedSubscriptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy 1-year subscription {0}.
        /// </summary>
        public static string BuySubscriptionLabel {
            get {
                return ResourceManager.GetString("BuySubscriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device is configured to avoid making purchases.
        ///Please change device configuration to continue..
        /// </summary>
        public static string CannotMakePurchasesMessage {
            get {
                return ResourceManager.GetString("CannotMakePurchasesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Payment will be charged to iTunes Account at confirmation of purchase.
        ///• Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period.
        ///• Account will be charged for renewal within 24-hours prior to the end of the current period at the same cost.
        ///• Subscriptions and auto-renewal may be turned off by going to the user&apos;s Account Settings after purchase.
        ///    .
        /// </summary>
        public static string SubscriptionMessage {
            get {
                return ResourceManager.GetString("SubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium subscription.
        /// </summary>
        public static string SubscriptionTitleMessage {
            get {
                return ResourceManager.GetString("SubscriptionTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a valid subscription that expires on {0:D}..
        /// </summary>
        public static string ValidSubscriptionMessage {
            get {
                return ResourceManager.GetString("ValidSubscriptionMessage", resourceCulture);
            }
        }
    }
}
