//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class YouTubeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YouTubeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.Strings.YouTubeResources", typeof(YouTubeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create playlist.
        /// </summary>
        public static string CreatePlaylistLabel {
            get {
                return ResourceManager.GetString("CreatePlaylistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the playlist &quot;{0}&quot; from YouTube? videos in the playlist will not be deleted..
        /// </summary>
        public static string DeletePlaylistQuestion {
            get {
                return ResourceManager.GetString("DeletePlaylistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} playlists from YouTube? videos in the playlists will not be deleted..
        /// </summary>
        public static string DeletePlaylistsQuestion {
            get {
                return ResourceManager.GetString("DeletePlaylistsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the video &quot;{0}&quot; from YouTube?.
        /// </summary>
        public static string DeleteVideoQuestion {
            get {
                return ResourceManager.GetString("DeleteVideoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove these {0} videos from YouTube?.
        /// </summary>
        public static string DeleteVideosQuestion {
            get {
                return ResourceManager.GetString("DeleteVideosQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeddable.
        /// </summary>
        public static string EmbeddableLabel {
            get {
                return ResourceManager.GetString("EmbeddableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no videos in this playlist..
        /// </summary>
        public static string EmptyPlaylistMessage {
            get {
                return ResourceManager.GetString("EmptyPlaylistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open video in YouTube.
        /// </summary>
        public static string OpenVideoLabel {
            get {
                return ResourceManager.GetString("OpenVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string PrivacyLabel {
            get {
                return ResourceManager.GetString("PrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string PrivateLabel {
            get {
                return ResourceManager.GetString("PrivateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string PublicLabel {
            get {
                return ResourceManager.GetString("PublicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsLabel {
            get {
                return ResourceManager.GetString("TagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlisted.
        /// </summary>
        public static string UnlistedLabel {
            get {
                return ResourceManager.GetString("UnlistedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        public static string WhereLabel {
            get {
                return ResourceManager.GetString("WhereLabel", resourceCulture);
            }
        }
    }
}
