//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open.FileExplorer.GoogleDrive.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoogleDriveResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleDriveResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Open.FileExplorer.GoogleDrive.Strings.GoogleDriveResources", typeof(GoogleDriveResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete forever.
        /// </summary>
        public static string DeleteForeverLabel {
            get {
                return ResourceManager.GetString("DeleteForeverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trash is empty..
        /// </summary>
        public static string EmptyTrashMessage {
            get {
                return ResourceManager.GetString("EmptyTrashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Photos.
        /// </summary>
        public static string GooglePhotosLabel {
            get {
                return ResourceManager.GetString("GooglePhotosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Drive.
        /// </summary>
        public static string MyDriveLabel {
            get {
                return ResourceManager.GetString("MyDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from trash.
        /// </summary>
        public static string RestoreFromTrashLabel {
            get {
                return ResourceManager.GetString("RestoreFromTrashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        public static string SharedWithMeLabel {
            get {
                return ResourceManager.GetString("SharedWithMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starred.
        /// </summary>
        public static string StarredLabel {
            get {
                return ResourceManager.GetString("StarredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string TrashLabel {
            get {
                return ResourceManager.GetString("TrashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the device authentication manager allows accessing the information without having to enter the password, but it is necessary your Google account to be registered in the device. 
        ///Use device authentication manager?.
        /// </summary>
        public static string UseDeviceAuthenticationManagerQuestion {
            get {
                return ResourceManager.GetString("UseDeviceAuthenticationManagerQuestion", resourceCulture);
            }
        }
    }
}
